
development:
  adapter: yaml
  db_dir_path: 'db/propro_yaml_dbs'

test:
  adapter: yaml
  db_dir_path: 'db/propro_yaml_dbs'

production:
  adapter: mongodb
  mdb_host: <%=ENV['OPENSHIFT_MONGODB_DB_HOST']%>
  mdb_port: <%=ENV['OPENSHIFT_MONGODB_DB_PORT']%>
  mdb_user: <%=ENV['OPENSHIFT_MONGODB_DB_USERNAME']%>
  mdb_pass: <%=ENV['OPENSHIFT_MONGODB_DB_PASSWORD']%>
  mdb_dbname: <%=ENV['OPENSHIFT_APP_NAME']%>

